version: "3"
services:
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - 8787:80
  krakend_ce:
    image: devopsfaith/krakend:1.2.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
